import {fresh,hydrate,CLASSES,d,check,combatAction,evidence,endingText} from './engine.mjs';
import {AREAS,getNode,applyChoice,objective} from './story.mjs';
import {World} from './world.mjs';
const $=id=>document.getElementById(id),KEY='nebelpfad.part1.v1';
let state=null,currentNode=null,selectedRole='wanderer',soundOn=false,audio=null,audioNodes=[],lastJournal=0,toastTimer,saving=true,choiceBusy=false;
const modal=$('dialog'),diceModal=$('dice-dialog');
function element(tag,text,className){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e;}
function button(label,fn,cls='choice'){const b=element('button',label,cls);b.type='button';b.addEventListener('click',fn);return b;}
function paragraphs(text,parent=$('dialog-text')){parent.replaceChildren();String(text).split('\n\n').forEach(p=>parent.append(element('p',p)));}
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3300);}
function readSave(){try{const raw=localStorage.getItem(KEY);return raw?hydrate(JSON.parse(raw)):null;}catch{return null;}}
function save(){if(!state)return;state.savedAt=new Date().toISOString();try{localStorage.setItem(KEY,JSON.stringify(state));$('save-status').textContent='✓ Dein Weg ist gespeichert';saving=true;}catch{$('save-status').textContent='Speichern nicht möglich · bitte Spielstand exportieren';saving=false;}}
const world=new World($('world'),()=>state,id=>{save();if(id)showNode(id);},toast);
function update(){if(!state)return;const a=AREAS[state.area],c=CLASSES[state.role];$('area-name').textContent=a.name;$('area-sub').textContent=a.sub;$('hero-name').textContent=state.name;$('health-text').textContent=`${state.hp}/${c.hp}`;$('health-fill').style.width=(state.hp/c.hp*100)+'%';$('potion-count').textContent=`♜ ${state.potions}`;$('objective').textContent=objective(state);$('journal-dot').hidden=state.journal.length<=lastJournal;}
function enter(s){state=s;$('start').hidden=true;$('game').hidden=false;world.sync();update();save();if(state.ending)showEpilogue();else if(!state.flags.intro)showNode('intro');else if(state.area===1&&!state.flags.villageIntro)showNode('villageIntro');else if(state.area===2&&!state.flags.archiveIntro)showNode('archiveIntro');else if(state.area===3&&!state.flags.sanctumIntro)showNode('sanctumIntro');}
function openDialog(speaker,title,text){modal.classList.remove('combat-dialog');$('speaker').textContent=speaker;$('dialog-title').textContent=title;paragraphs(text);$('dialog-extra').replaceChildren();$('choices').replaceChildren();$('dialog-close').hidden=false;if(!modal.open)modal.showModal();modal.scrollTop=0;}
function showNode(id){if(!state)return;if(state.ending){showEpilogue();return;}if(id==='ending'){showEpilogue();return;}currentNode=id;const node=getNode(state,id);openDialog(node.speaker,node.title,node.text);node.choices.forEach(ch=>{const b=button(ch.label,()=>takeChoice(ch),ch.ending?'choice gold':'choice');b.disabled=!!ch.disabled;if(ch.disabled&&ch.hint)b.append(element('small',ch.hint));if(ch.test){const bonus=CLASSES[state.role].skills[ch.test.skill];b.append(element('small',`W20 + ${bonus} · Schwierigkeit ${ch.test.dc}${ch.test.advantage?' · Vorteil':''}`));}$('choices').append(b);});}
async function takeChoice(ch){if(choiceBusy||ch.disabled)return;choiceBusy=true;try{let dice=[];if(ch.test){modal.close();dice=await rollCheck(ch.test);}const oldArea=state.area,result=applyChoice(state,ch,dice);update();save();if(oldArea!==state.area)world.sync();if(ch.combat){currentNode=null;if(state.combat)showCombat();else{world.sync();showNode('guardian');toast('Mara hat dich zurückgezogen. Du kannst einen anderen Weg suchen.');}return;}if(result.node)showNode(result.node);else{modal.close();currentNode=null;if(state.ending)toast('Dein Ende ist gespeichert. Teil 2 kann daran anknüpfen.');}}finally{choiceBusy=false;}}
function rollCheck(spec){return new Promise(resolve=>{const names={medicine:'Heilkunde',athletics:'Athletik',investigation:'Nachforschungen',persuasion:'Überreden',insight:'Motiv erkennen'};const bonus=CLASSES[state.role].skills[spec.skill];$('dice-label').textContent=spec.advantage?'MARA HILFT DIR · VORTEIL':'DEIN MOMENT';$('dice-title').textContent=names[spec.skill];$('die').textContent='?';$('dice-equation').textContent=`W20 + ${bonus} · Ziel ${spec.dc}`;$('dice-explain').textContent=spec.advantage?'Zwei Würfel. Der höhere zählt.':'Würfel + Bonus müssen mindestens das Ziel erreichen.';$('roll-button').textContent='Würfel werfen';$('roll-button').disabled=false;diceModal.showModal();$('roll-button').onclick=async()=>{$('roll-button').disabled=true;const dice=spec.advantage?[d(20),d(20)]:[d(20)];const result=check(state,spec.skill,spec.dc,dice[0],spec.advantage?dice[1]:null);$('die').classList.add('rolling');tone(240,.15);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let step=0;const ticker=setInterval(()=>{$('die').textContent=String((step++*7)%20+1);},65);await new Promise(r=>setTimeout(r,reduced?100:750));clearInterval(ticker);$('die').classList.remove('rolling');$('die').textContent=result.roll;$('dice-equation').textContent=`${result.roll} + ${bonus} = ${result.total} · ${result.success?'Erfolg':'Fehlschlag'}`;$('dice-explain').textContent=`Ziel: ${spec.dc}${spec.advantage?' · Gewürfelt: '+dice.join(' und '):''}. ${result.success?'Du findest deinen Weg.':'Die Geschichte geht weiter.'}`;tone(result.success?440:140,.3);if(navigator.vibrate)navigator.vibrate(result.success?35:[20,50,20]);$('roll-button').textContent='Weiter';$('roll-button').disabled=false;$('roll-button').onclick=()=>{diceModal.close();resolve(dice);};};});}
diceModal.addEventListener('cancel',e=>e.preventDefault());
function showCombat(){if(!state.combat)return;const b=state.combat;openDialog('BEGEGNUNG · RUNDE '+b.round,'Der Vertragswächter',`Du ${state.hp}/${CLASSES[state.role].hp} LP · Wächter ${b.hp}/${b.maxHp} LP\n\nDu wählst eine Aktion. Danach handelt der Wächter. Treffer: W20 + Angriffsbonus gegen Rüstungsklasse 12.`);modal.classList.add('combat-dialog');$('dialog-close').hidden=true;const bar=element('div',undefined,'combat-bar'),fill=element('span');fill.style.width=b.hp/b.maxHp*100+'%';bar.append(fill);$('dialog-extra').append(bar,element('p',b.log,'combat-log'));for(const [label,act]of [[`Angreifen · ${CLASSES[state.role].weapon}`,'attack'],['Mara um eine Lücke bitten · nächste Attacke mit Vorteil','help'],['Ausweichen · Gegner hat Nachteil','dodge'],[`Heiltrank trinken · noch ${state.potions}`,'potion'],['Zurückziehen · andere Lösung suchen','flee']]){const btn=button(label,()=>battle(act));btn.disabled=act==='potion'&&!state.potions;$('choices').append(btn);}}
function battle(act){const result=combatAction(state,act);update();save();tone(act==='attack'?170:320,.15);$('world-frame').classList.remove('battle-flash');void $('world-frame').offsetWidth;$('world-frame').classList.add('battle-flash');if(result.result==='victory'){openDialog('DER WEG IST FREI','Ein Versprechen zerbricht',result.log+'\n\nDer Wächter sinkt auf die Knie. „Schutz … aufrechterhalten.“ Dann erlischt sein Licht. Hinter ihm öffnet sich der Durchgang.');$('choices').append(button('Zurück ins Archiv',()=>modal.close()));}else if(result.result==='defeat'){world.sync();openDialog('MARA','Du bist noch hier','Mara zieht dich hinter eine Steinplatte. Als der Wächter zum Tor zurückkehrt, verbindet sie deine Wunden. Du erholst dich auf die Hälfte deiner Lebenspunkte.\n\n„Wir können es noch einmal versuchen. Oder ihm mit Beweisen zeigen, dass er falschliegt.“');$('choices').append(button('Nach einem anderen Weg suchen',()=>modal.close()));}else if(result.result==='flee'){modal.close();toast('Du ziehst dich zurück. Alle Hinweise bleiben erhalten.');}else showCombat();}
modal.addEventListener('cancel',e=>{if(state?.combat)e.preventDefault();});$('dialog-close').onclick=()=>{if(!state?.combat)modal.close();};
function showCreation(){selectedRole='wanderer';openDialog('DEINE REISE','Wer geht diesen Weg?','Du bist jung, unerfahren und zum ersten Mal allein mit deinen Entscheidungen. Mara begleitet dich. Dein Weg ist noch nicht festgeschrieben.');const label=element('label','Dein Name','field-label');label.htmlFor='name-input';const input=element('input');input.id='name-input';input.type='text';input.maxLength=24;input.value='Ari';input.autocomplete='off';const list=element('div',undefined,'role-list');for(const [key,c]of Object.entries(CLASSES)){const b=button('',()=>{selectedRole=key;list.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));},'role-card');b.setAttribute('aria-pressed',String(key===selectedRole));b.append(element('strong',c.name),element('small',c.subtitle),element('small',`${c.hp} Lebenspunkte · Rüstung ${c.ac} · ${c.weapon}`));list.append(b);}$('dialog-extra').append(label,input,element('label','Dein erster Weg','field-label'),list,element('p','Einsteigerprofile auf Stufe 1. Du lernst jede Regel erst, wenn du sie brauchst.','small-note'));$('choices').append(button('Die Laterne nehmen und aufbrechen',()=>{const name=input.value;modal.close();enter(fresh(name,selectedRole));},'primary'));}
$('new-game').onclick=()=>{if(readSave()){openDialog('NEUER ANFANG','Einen neuen Weg beginnen?','Dein bisheriger Spielstand wird erst beim Aufbruch ersetzt. Du kannst ihn vorher über „Spielstand sichern“ im Menü exportieren.');$('choices').append(button('Neuen Helden anlegen',showCreation),button('Zurück',()=>modal.close()));}else showCreation();};$('continue').onclick=()=>{const s=readSave();if(s)enter(s);};$('continue').hidden=!readSave();if(readSave())$('new-game').className='quiet';
$('places').onclick=()=>{openDialog('DEINE UMGEBUNG',AREAS[state.area].name,'Wähle einen Ort. Dein Held läuft dorthin.');for(const h of AREAS[state.area].hotspots)$('choices').append(button(h.name,()=>{modal.close();world.go(h);}));};
$('journal').onclick=()=>{lastJournal=state.journal.length;update();openDialog('WAS BLEIBT','Dein Tagebuch',state.journal.length?'Hinweise, Begegnungen und Entscheidungen.':'Deine erste Seite wartet auf dich.');for(const entry of state.journal){const div=element('section',undefined,'journal-entry');div.append(element('h3',entry.title),element('p',entry.text));$('dialog-extra').append(div);}if(state.rolls.length){$('dialog-extra').append(element('h3','Die letzten Würfe'),element('div',state.rolls.join('\n'),'roll-history'));}if(state.ending)$('choices').append(button('Deinen Epilog lesen',showEpilogue));};
$('character').onclick=()=>{const c=CLASSES[state.role];openDialog('DEIN HELD · STUFE 1',state.name,c.name+' · '+c.subtitle);const stats=element('div',undefined,'info-grid');for(const [v,k]of [[state.hp+'/'+c.hp,'Lebenspunkte'],[c.ac,'Rüstung'],['+'+c.attack,'Angriff']]){const e=element('div',undefined,'stat');e.append(element('b',String(v)),element('span',k));stats.append(e);}$('dialog-extra').append(stats,element('p',`Nachforschungen +${c.skills.investigation} · Athletik +${c.skills.athletics} · Heilkunde +${c.skills.medicine} · Überreden +${c.skills.persuasion}`,'small-note'),element('p','Gepäck: Runas Laterne, Reiserucksack, '+state.potions+' Heiltränke'+(state.flags.rope?', Maras Seil':'')+(state.flags.confession?', Wegwächterschlüssel':'')+'.','small-note'));if(state.hp<c.hp&&state.potions>0)$('choices').append(button('Heiltrank trinken · 2W4 + 2',()=>{state.potions--;state.hp=Math.min(c.hp,state.hp+d(4)+d(4)+2);save();update();$('character').click();}));$('choices').append(button('Wie funktionieren die Regeln?',showRules));};
$('companion').onclick=()=>{if(state.area>=2)showNode('mara');else{openDialog('MARA · WEGWÄCHTERIN','An deiner Seite',state.flags.iven?'„Du hast deine erste Entscheidung getroffen. Jetzt geh weiter. Du musst nicht wissen, wie alles endet, um den nächsten Schritt zu machen.“':'„Tippe auf einen Weg, dann gehst du los. Tippe auf einen markierten Ort, dann sehen wir ihn uns an. Ich komme mit.“');$('choices').append(button('Erklär mir die Regeln',showRules),button('Weitergehen',()=>modal.close()));}};
function showRules(){openDialog('LERNEN UNTERWEGS','Würfel, Mut und Möglichkeiten','Bei einer Fertigkeitsprobe würfelst du einen W20 und addierst deinen Bonus. Erreichst du mindestens die Schwierigkeit, gelingt die Probe. Eine 20 oder 1 ist dabei nicht automatisch Erfolg oder Fehlschlag.\n\nVorteil: zwei W20, der höhere zählt. Nachteil: der niedrigere zählt. Im Kampf trifft eine natürliche 20 immer und verdoppelt die Schadenswürfel; eine natürliche 1 verfehlt. Andere Angriffe treffen, wenn W20 + Bonus mindestens die Rüstung erreicht.\n\nIm Kampf wählst du eine Aktion. Danach handelt der Wächter. Mara kann dir für deine nächste Attacke Vorteil verschaffen. Ein Trank heilt 2W4 + 2.\n\nDieses erste Abenteuer verwendet einen ausgewählten SRD-Regelkern mit klaren Hausregeln: feste Einsteigerprofile, vereinfachte Bewegung und Rast, Maras kombinierte Hilfe/Deckung und Rettung nach einer Niederlage. Es ist keine vollständige D&D-Simulation.');const p=element('p',undefined,'small-note');p.append('Regelgrundlage: ');const a=element('a','System Reference Document 5.2.1');a.href='https://www.dndbeyond.com/srd';a.target='_blank';a.rel='noopener';p.append(a,' by Wizards of the Coast LLC · CC BY 4.0. Eigene Welt und Figuren. ');const attribution=element('a','Vollständige Attribution');attribution.href='NOTICE.md';attribution.target='_blank';p.append(attribution);$('dialog-extra').append(p);$('choices').append(button('Verstanden',()=>modal.close()));}
function showEpilogue(){const e=endingText(state);if(!e)return;openDialog(e.kicker,e.title,e.text);$('dialog-extra').append(element('div','✧','ending-mark'),element('p',e.hook),element('p','ENDE VON TEIL I · FORTSETZUNG VORBEREITET','small-note'));$('choices').append(button('Vermächtnis für Teil 2 sichern',exportSave,'choice gold'),button('Tagebuch ansehen',()=>$('journal').click()),button('Zum Titelbild',toTitle));}
function exportSave(){if(!state)return;save();const payload={...state,continuity:{part:1,ending:state.ending,evidence:evidence(state),maraForgiven:!!state.flags.forgiven,ivenHelped:!!state.flags.ivenSaved,nextBeacon:'Aschenhafen'}};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=element('a');a.href=URL.createObjectURL(blob);a.download='nebelpfad-spielstand.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),3000);}
function toTitle(){modal.close();save();world.active=false;$('game').hidden=true;$('start').hidden=false;$('continue').hidden=false;$('new-game').className='quiet';}
$('menu').onclick=()=>{openDialog('DEIN WEG','Eine kleine Pause','Dein Fortschritt wird auf diesem Gerät gespeichert. Ein exportierter Spielstand sichert dein Vermächtnis auch für weitere Abenteuer.');$('choices').append(button('Weiterspielen',()=>modal.close()),button('Spielstand sichern',exportSave),button('Spielstand laden',()=>requestImport(true)),button('Regeln & Hilfe',showRules),button('Auf dem Handy installieren',()=>{openDialog('DEINE APP','Nebelpfad immer dabei','iPhone: In Safari auf Teilen tippen, dann „Zum Home-Bildschirm“.\n\nAndroid: Im Browsermenü „App installieren“ oder „Zum Startbildschirm hinzufügen“ wählen.\n\nNach dem ersten vollständigen Laden kann das Abenteuer auch offline gespielt werden. Spielstände bleiben auf diesem Gerät; zum Wechseln bitte exportieren.');}),button('Zum Titelbild',toTitle));if(!saving)$('dialog-extra').append(element('p','Dein Browser blockiert lokales Speichern. Bitte exportiere vor dem Schließen.','install-note'));};
function requestImport(confirm=false){if(confirm){openDialog('SPIELSTAND LADEN','Deinen aktuellen Weg ersetzen?','Der geladene Spielstand ersetzt den lokalen Fortschritt. Sichere ihn bei Bedarf zuerst.');$('choices').append(button('Aktuellen Spielstand sichern',exportSave),button('Datei auswählen',()=>$('import-file').click()),button('Abbrechen',()=>modal.close()));}else $('import-file').click();}
$('start-import').onclick=()=>requestImport(!!readSave());$('import-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>200000)throw Error('Die Datei ist zu groß.');const next=hydrate(JSON.parse(await file.text()));modal.close();enter(next);}catch(err){openDialog('NICHT GELADEN','Dieser Spielstand konnte nicht geladen werden',err.message||'Bitte wähle einen gültigen Spielstand.');}e.target.value='';};
function tone(freq,seconds){if(!soundOn||!audio)return;const osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.frequency.value=freq;gain.gain.setValueAtTime(.06,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+seconds);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+seconds);}
async function toggleSound(){try{if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();await audio.resume();soundOn=!soundOn;for(const n of audioNodes)n.stop();audioNodes=[];if(soundOn){for(const [freq,vol]of [[110,.015],[164.81,.009],[220,.004]]){const osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.frequency.value=freq;gain.gain.value=vol;osc.connect(gain);gain.connect(audio.destination);osc.start();audioNodes.push(osc);}}$('sound').setAttribute('aria-pressed',String(soundOn));$('sound').setAttribute('aria-label',soundOn?'Klang ausschalten':'Klang einschalten');$('sound').style.color=soundOn?'#f7d190':'';toast(soundOn?'Atmosphärischer Klang eingeschaltet':'Klang ausgeschaltet');}catch{toast('Dein Browser kann den Klang gerade nicht starten.');}}
$('sound').onclick=toggleSound;document.addEventListener('visibilitychange',()=>{if(document.hidden){save();audio?.suspend();}else if(soundOn)audio?.resume();});window.addEventListener('pagehide',save);window.addEventListener('keydown',e=>{if(!state||!world.active||modal.open||diceModal.open||!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key))return;e.preventDefault();const dx=['ArrowRight','d'].includes(e.key)?.065:['ArrowLeft','a'].includes(e.key)?-.065:0,dy=['ArrowDown','s'].includes(e.key)?.065:['ArrowUp','w'].includes(e.key)?-.065:0;world.go({x:world.hero.x+dx,y:world.hero.y+dy});});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
