export const VERSION=1;
export const CLASSES={
 wanderer:{name:'Wegläufer',subtitle:'Aufmerksam. Beweglich. Schwer zu täuschen.',hp:12,ac:14,attack:4,damage:6,bonus:2,skills:{athletics:2,investigation:3,insight:3,persuasion:2,medicine:1},weapon:'Kurzschwert'},
 guardian:{name:'Hüter',subtitle:'Ein fester Stand, wenn die Welt ins Wanken gerät.',hp:15,ac:16,attack:5,damage:8,bonus:3,skills:{athletics:5,investigation:1,insight:1,persuasion:2,medicine:1},weapon:'Langschwert'},
 scholar:{name:'Funkenkundige',subtitle:'Du erkennst Muster, wo andere nur Dunkelheit sehen.',hp:10,ac:12,attack:5,damage:10,bonus:0,skills:{athletics:0,investigation:5,insight:3,persuasion:2,medicine:2},weapon:'Feuerfunke'}
};
export const FLAG_KEYS=['intro','trail','iven','medicineGiven','ivenSaved','inscription','bridge','rope','villageIntro','ledger','well','bell','archiveIntro','mural','confession','forgiven','guardian','guardianPeace','guardianTried','rested','sanctumIntro','truth','end'];
export function fresh(name='Ari',role='wanderer'){const c=CLASSES[role]||CLASSES.wanderer;return {version:VERSION,name:String(name).trim().slice(0,24)||'Ari',role:CLASSES[role]?role:'wanderer',area:0,hp:c.hp,potions:2,trust:0,flags:{},journal:[],rolls:[],combat:null,ending:null,position:{x:.5,y:.82},savedAt:null};}
export function d(sides=20){const max=Math.floor(4294967296/sides)*sides;const a=new Uint32Array(1);do{crypto.getRandomValues(a)}while(a[0]>=max);return a[0]%sides+1;}
export function check(state,skill,dc,roll=d(20),advantageRoll=null){const bonus=CLASSES[state.role].skills[skill]||0;const used=advantageRoll===null?roll:Math.max(roll,advantageRoll);return {roll:used,dice:advantageRoll===null?[roll]:[roll,advantageRoll],bonus,total:used+bonus,dc,success:used+bonus>=dc};}
export function evidence(s){return ['ledger','well','mural'].filter(k=>s.flags[k]).length;}
export function log(s,title,text){if(!s.journal.some(x=>x.title===title))s.journal.push({title,text});}
export function startCombat(s,roll=d){const initiative=roll(20)+2,enemyInitiative=roll(20)+1;s.combat={hp:16,maxHp:16,round:1,guard:false,insight:false,initiative,enemyInitiative,log:`Initiative: du ${initiative}, Wächter ${enemyInitiative}.`,last:null};if(enemyInitiative>initiative)enemyTurn(s,roll);return s;}
function enemyTurn(s,roll){if(!s.combat)return;const b=s.combat;const raw=roll(20),other=b.guard?roll(20):raw,die=Math.min(raw,other),total=die+3;const hit=die===20||(die!==1&&total>=CLASSES[s.role].ac);let damage=hit?roll(4)+1+(die===20?roll(4):0):0;s.hp=Math.max(0,s.hp-damage);b.last={actor:'enemy',die,total,hit,damage};b.log+=hit?` Der Wächter trifft (${die}+3) für ${damage} Schaden.`:` Der Wächter verfehlt (${die}+3).`;b.guard=false;b.round++;if(s.hp===0){s.hp=Math.ceil(CLASSES[s.role].hp/2);s.combat=null;s.area=2;s.position={x:.5,y:.82};log(s,'Vom Wächter zurückgedrängt','Mara zog dich aus dem Archivkampf. Eine kurze Erholung bringt dich wieder auf die Beine. Der Wächter bleibt am Tor.');return 'defeat';}}
export function combatAction(s,action,roll=d){if(!s.combat)return {result:'inactive'};const b=s.combat;b.log='';if(action==='flee'){s.combat=null;log(s,'Ein anderer Weg','Du hast den Kampf abgebrochen. Hinweise und ein Gespräch können den Wächter ebenfalls überzeugen.');return {result:'flee'};}if(action==='potion'){if(s.potions<1)return {result:'no-potion'};s.potions--;const healed=roll(4)+roll(4)+2;s.hp=Math.min(CLASSES[s.role].hp,s.hp+healed);b.log=`Trank: ${healed} Heilung (2W4+2).`;}else if(action==='dodge'){b.guard=true;b.log='Du weichst aus. Der nächste Angriff des Wächters hat Nachteil.';}else if(action==='help'){b.insight=true;b.guard=true;b.log='Mara zeigt dir eine Lücke: Vorteil auf deinen nächsten Angriff. Du gehst in Deckung.';}else if(action==='attack'){const raw=roll(20),second=b.insight?roll(20):raw,die=Math.max(raw,second);b.insight=false;const c=CLASSES[s.role],hit=die===20||(die!==1&&die+c.attack>=12);const damage=hit?roll(c.damage)+(die===20?roll(c.damage):0)+c.bonus:0;b.hp=Math.max(0,b.hp-damage);b.last={actor:'hero',die,total:die+c.attack,hit,damage};b.log=hit?`${c.weapon}: ${die}+${c.attack} trifft. ${damage} Schaden${die===20?' – kritischer Treffer!':''}.`:`${c.weapon}: ${die}+${c.attack}. Verfehlt.`;if(b.hp===0){s.combat=null;s.flags.guardian=true;log(s,'Der zerbrochene Wächter','Der Wächter verstummt. Sein letzter Satz: „Ich habe nur das Versprechen gehalten.“');return {result:'victory',log:b.log};}}else return {result:'invalid'};const result=enemyTurn(s,roll);return {result:result||'turn',log:b.log};}
export function endingText(s){const shared=s.flags.medicineGiven?'Iven erreicht das Dorf mit deiner Medizin. Die Zurückgekehrten sind schwach, aber sie sind nicht allein.':s.flags.ivenSaved?'Iven kehrt mit einem Verband und einer langen Liste von Namen zurück. Er will helfen.':'Iven bleibt am Weglager. Als der Nebel fällt, folgen die ersten Dorfbewohner seinem Feuer.';const mara=s.flags.forgiven?'Mara geht neben dir. Euer Vertrauen ist kein Freispruch. Es ist eine Entscheidung für den nächsten Schritt.':'Mara folgt mit Abstand. Zwischen euch bleibt eine Wahrheit, die nicht durch einen Sieg verschwindet.';const ends={release:{title:'Ein Morgen ohne Schutz',kicker:'ENDE I · FREIHEIT',text:`Du löschst den Kern. Erst fällt die Stille, dann der Regen. Menschen stehen wieder auf dem Dorfplatz, erschrocken, nass, lebendig. Der alte Schutz ist fort. Zum ersten Mal seit siebzehn Jahren gehört das nächste Versprechen ihnen selbst. ${shared} ${mara}`,hook:'In der erloschenen Laterne glimmt eine Karte auf: sechs weitere Leuchtfeuer. Eines sendet ein Signal in der Handschrift deiner Mutter.'},renew:{title:'Die Stimme, die fehlt',kicker:'ENDE II · OPFER',text:`Du gibst dem Kern eine einzige Erinnerung: die Stimme deiner Mutter. Ihr Gesicht bleibt dir, ihr Name bleibt dir. Aber wenn du an ihr Lied denkst, bewegt sich in deinem Gedächtnis nur noch ihr Mund. Der Kern gibt die Menschen frei. Der Schutz hält sieben Nächte; der Preis verlängert ihn ausdrücklich nicht darüber hinaus. ${shared} ${mara}`,hook:'Sieben Nächte bleiben, um das nächste Leuchtfeuer zu erreichen. Mara kennt den Weg. Ob sie alle Wegmarken noch kennt, sagt sie nicht.'},share:{title:'Kein Name allein',kicker:'ENDE III · EIN NEUER VERTRAG',text:`Mit den Namen aus dem Register und den Antworten der Eingeschlossenen öffnest du einen Rückweg. Zum ersten Mal müssen sie selbst antworten. Einige stimmen zu, andere nicht. Beide Gruppen kehren zurück. Die Zustimmenden tragen den Schutz gemeinsam; wer ablehnt, schuldet nichts. Er ist schwächer, aber er gehört niemandem mehr allein. ${shared} ${mara}`,hook:'Im Register erscheint eine neue Zeile: „Gegenzeichnung angefordert. Leuchtfeuer II: Aschenhafen.“ Daneben steht der Name deiner Mutter – datiert auf morgen.'}};return ends[s.ending]||null;}
export function hydrate(raw){if(!raw||typeof raw.name!=='string'||raw.version!==VERSION||!CLASSES[raw.role]||!Number.isInteger(raw.area)||raw.area<0||raw.area>3)throw Error('Dieser Spielstand passt nicht zu Teil 1.');const s=fresh(raw.name,raw.role);s.area=raw.area;s.hp=Math.min(CLASSES[s.role].hp,Math.max(1,Number(raw.hp)||1));s.potions=Math.min(2,Math.max(0,Math.floor(Number(raw.potions)||0)));s.trust=Math.min(10,Math.max(-10,Number(raw.trust)||0));s.flags=Object.fromEntries(FLAG_KEYS.filter(k=>raw.flags?.[k]===true).map(k=>[k,true]));s.journal=Array.isArray(raw.journal)?raw.journal.slice(0,60).filter(x=>typeof x.title==='string'&&typeof x.text==='string').map(x=>({title:x.title.slice(0,100),text:x.text.slice(0,2000)})):[];s.rolls=Array.isArray(raw.rolls)?raw.rolls.slice(-20).filter(x=>typeof x==='string').map(x=>x.slice(0,200)):[];s.ending=['release','renew','share'].includes(raw.ending)?raw.ending:null;s.position={x:Math.min(.86,Math.max(.14,Number(raw.position?.x)||.5)),y:Math.min(.9,Math.max(.2,Number(raw.position?.y)||.82))};s.savedAt=raw.savedAt||null;return s;}
