export const VERSION=1;
export const CLASSES={
 wanderer:{name:'Wegläufer',subtitle:'Aufmerksam. Beweglich. Schwer zu täuschen.',hp:12,ac:14,attack:4,damage:6,bonus:2,skills:{athletics:2,investigation:3,insight:3,persuasion:2,medicine:1},weapon:'Kurzschwert'},
 guardian:{name:'Hüter',subtitle:'Ein fester Stand, wenn die Welt ins Wanken gerät.',hp:15,ac:16,attack:5,damage:8,bonus:3,skills:{athletics:5,investigation:1,insight:1,persuasion:2,medicine:1},weapon:'Langschwert'},
 scholar:{name:'Funkenkundige',subtitle:'Du erkennst Muster, wo andere nur Dunkelheit sehen.',hp:10,ac:12,attack:5,damage:10,bonus:0,skills:{athletics:0,investigation:5,insight:3,persuasion:2,medicine:2},weapon:'Feuerfunke'}
};
export const FLAG_KEYS=['intro','trail','iven','medicineGiven','ivenSaved','inscription','bridge','rope','villageIntro','ledger','well','bell','archiveIntro','mural','guardian','guardianPeace','guardianTried','rested','sanctumIntro','truth','end'];
export function fresh(name='Ari',role='wanderer'){const c=CLASSES[role]||CLASSES.wanderer;return {version:VERSION,storyRevision:2,name:String(name).trim().slice(0,24)||'Ari',role:CLASSES[role]?role:'wanderer',area:0,hp:c.hp,potions:2,trust:0,flags:{},journal:[],rolls:[],combat:null,ending:null,position:{x:.5,y:.82},savedAt:null};}
export function d(sides=20){const max=Math.floor(4294967296/sides)*sides;const a=new Uint32Array(1);do{crypto.getRandomValues(a)}while(a[0]>=max);return a[0]%sides+1;}
export function check(state,skill,dc,roll=d(20),advantageRoll=null){const bonus=CLASSES[state.role].skills[skill]||0;const used=advantageRoll===null?roll:Math.max(roll,advantageRoll);return {roll:used,dice:advantageRoll===null?[roll]:[roll,advantageRoll],bonus,total:used+bonus,dc,success:used+bonus>=dc};}
export function evidence(s){return ['ledger','well','mural'].filter(k=>s.flags[k]).length;}
export function log(s,title,text){if(!s.journal.some(x=>x.title===title))s.journal.push({title,text});}
export function startCombat(s,roll=d){const initiative=roll(20)+2,enemyInitiative=roll(20)+1;s.combat={hp:16,maxHp:16,round:1,guard:false,insight:false,initiative,enemyInitiative,log:`Initiative: du ${initiative}, Wächter ${enemyInitiative}.`,last:null};if(enemyInitiative>initiative)enemyTurn(s,roll);return s;}
function enemyTurn(s,roll){if(!s.combat)return;const b=s.combat;const raw=roll(20),other=b.guard?roll(20):raw,die=Math.min(raw,other),total=die+3;const hit=die===20||(die!==1&&total>=CLASSES[s.role].ac);let damage=hit?roll(4)+1+(die===20?roll(4):0):0;s.hp=Math.max(0,s.hp-damage);b.last={actor:'enemy',die,total,hit,damage};b.log+=hit?` Der Wächter trifft (${die}+3) für ${damage} Schaden.`:` Der Wächter verfehlt (${die}+3).`;b.guard=false;b.round++;if(s.hp===0){s.hp=Math.ceil(CLASSES[s.role].hp/2);s.combat=null;s.area=2;s.position={x:.5,y:.82};log(s,'Vom Wächter zurückgedrängt','Du konntest dich hinter eine schmale Steinrippe zurückziehen. Der Wächter bewacht nur das Tor und verfolgt dich nicht. Du versorgst deine Wunden.');return 'defeat';}}
export function combatAction(s,action,roll=d){if(!s.combat)return {result:'inactive'};const b=s.combat;b.log='';if(action==='flee'){s.combat=null;log(s,'Ein anderer Weg','Du hast den Kampf abgebrochen. Hinweise und ein Gespräch können den Wächter ebenfalls überzeugen.');return {result:'flee'};}if(action==='potion'){if(s.potions<1)return {result:'no-potion'};s.potions--;const healed=roll(4)+roll(4)+2;s.hp=Math.min(CLASSES[s.role].hp,s.hp+healed);b.log=`Trank: ${healed} Heilung (2W4+2).`;}else if(action==='dodge'){b.guard=true;b.log='Du weichst aus. Der nächste Angriff des Wächters hat Nachteil.';}else if(action==='focus'){b.insight=true;b.guard=true;b.log='Du beobachtest hinter der Steinrippe den Rhythmus der Zahnräder. Dein nächster Angriff hat Vorteil, der nächste Gegenangriff Nachteil.';}else if(action==='attack'){const raw=roll(20),second=b.insight?roll(20):raw,die=Math.max(raw,second);b.insight=false;const c=CLASSES[s.role],hit=die===20||(die!==1&&die+c.attack>=12);const damage=hit?roll(c.damage)+(die===20?roll(c.damage):0)+c.bonus:0;b.hp=Math.max(0,b.hp-damage);b.last={actor:'hero',die,total:die+c.attack,hit,damage};b.log=hit?`${c.weapon}: ${die}+${c.attack} trifft. ${damage} Schaden${die===20?' – kritischer Treffer!':''}.`:`${c.weapon}: ${die}+${c.attack}. Verfehlt.`;if(b.hp===0){s.combat=null;s.flags.guardian=true;log(s,'Der zerbrochene Wächter','Der Wächter verstummt. Sein letzter Satz: „Ich habe nur das Versprechen gehalten.“');return {result:'victory',log:b.log};}}else return {result:'invalid'};const result=enemyTurn(s,roll);return {result:result||'turn',log:b.log};}
export function endingText(s){
const iven=s.flags.medicineGiven?'Am Abend kommt Iven über den Steg. Er humpelt, doch der Verband hält. In der Heilstube fragt er, wo er helfen kann.':s.flags.ivenSaved?'Iven erreicht das Dorf, auf einen Ast gestützt. Du zeigst ihm die Heilstube. Als man ihn fragt, was geschehen ist, legt er seinen Zustellbeleg auf den Tisch.':s.flags.iven?'Du erzählst Elin von dem Verletzten am Weg. Zwei Dorfbewohner holen Iven, bevor es dunkel wird. Er hat seinen Zustellbeleg nicht ins Feuer geworfen.':'Am Abend bringen zwei Dorfbewohner einen verletzten Boten vom Weglager herein. Er heißt Iven. Aus seiner Tasche zieht er den Beleg für einen Brief, den er heute Morgen zur Kapelle brachte.';
const guardian=s.flags.guardianPeace?'Unten im Archiv wartet der Wächter auf neue Anweisungen. Diesmal werden die Bewohner selbst daran mitwirken.':'Das Tor im Archiv bleibt unbewacht. Die Dorfbewohner werden die Anlage selbst instand halten müssen.';
const revelation=s.flags.truth?'Du breitest Runas Brief neben Ivens Zustellbeleg aus. Beide führen nach Aschenhafen. Vor drei Jahren wollte deine Mutter dort die Bewahrung verhindern. Heute hat dieselbe Zentrale sie angeordnet.':'Iven zeigt dir seinen Zustellbeleg: Die Anweisung zur Bewahrung kam aus Aschenhafen. Elin kennt den Namen deiner Mutter aus dem Dorfbuch. „Sie wollte zur Zentrale“, erinnert sie sich. „Das war vor drei Jahren. Danach kam kein Brief mehr.“';
const ends={
release:{title:'Ein Morgen ohne Schutz',kicker:'',text:`Du drehst den Lösungsring. Licht strömt durch die Leitungen nach oben. Erst als die letzte Gestalt verschwunden ist, löschst du den Kern. Die Kammer wird dunkel.\n\nAuf dem Dorfplatz findest du Menschen, die sich aneinander festhalten. Elin sitzt neben dem Brunnen und bindet ihrer Tochter einen Schuh. Eine so gewöhnliche Bewegung, dass du eine Weile nicht wegsehen kannst.\n\nDu sagst ihnen, was du getan hast. Noch in derselben Nacht beginnen sie, Wagen zu beladen und Vorräte für den nächsten Sturm zusammenzutragen. Manche danken dir. Andere fragen, wohin sie jetzt sollen. Du hast darauf noch keine Antwort.\n\n${iven}\n\n${guardian}`,hook:`${revelation}\n\nAm nächsten Morgen zeigt dir Elin die Straße zum Hafen. „Wenn du etwas findest, schick Nachricht.“ Du versprichst es. Hinter dir gehen die Lichter in Dornwacht an – kleine Feuer, von Menschen entzündet. Deine Reise nach Aschenhafen beginnt.`},
renew:{title:'Die Stimme, die fehlt',kicker:'',text:`Du erinnerst dich an das Lied. An den Wind vor dem Fenster. An die Hand auf deiner Decke. Dann ist da eine Lücke, wo die Stimme war.\n\nDu weißt noch, dass deine Mutter gesungen hat. Du kannst keinen einzigen Ton mehr heraufholen. Im Kern springen sieben kleine Lichter an. Eines für jede Nacht. Die Gefangenen verschwinden aus der Hülle; von oben dringen Rufe herab.\n\nAuf dem Platz hält Elin ihre Tochter fest. Du sagst den Menschen, wie viel Zeit ihnen bleibt. Die Erleichterung weicht ernstem Schweigen. Dann beginnt jemand, die Heilstube herzurichten.\n\n${iven}\n\n${guardian}`,hook:`${revelation}\n\nAschenhafen liegt zwei Tagesmärsche entfernt. Du wirst dort nach einer dauerhaften Lösung suchen müssen, während Dornwacht seine Flucht vorbereitet. Als du aufbrichst, versuchst du noch einmal, das Lied zu erinnern. Nichts. Sechs volle Nächte bleiben nach dieser ersten Nacht.`},
share:{title:'Was wir einander versprechen',kicker:'',text:`Du zeichnest die Vereinbarung gegen. Der Mann, der nichts geben wollte, tritt als Erster aus dem Licht. Dann Elin, Lene und alle anderen. Kein Name bleibt zurück.\n\nAls du auf den Dorfplatz kommst, stehen sie noch zwischen Brunnen und Heilstube. Elin blickt zum verwilderten Garten hinter der Kapelle. „War der immer da?“, fragt sie. Du antwortest, obwohl du weißt, dass das nicht ihre eigentliche Frage ist.\n\nÜber den Dächern glimmt das Leuchtfeuer. Sein Schein reicht nicht mehr bis zum Waldrand. Die Bewohner werden gemeinsam entscheiden müssen, was sie beim nächsten Sturm tun. Doch keiner wird dafür gegen seinen Willen verschwinden.\n\n${iven}\n\n${guardian}`,hook:`${revelation}\n\nBevor du gehst, kommt Lene mit einem zusammengerollten Blatt auf dich zu. Sie hat eine Laterne gemalt und alle Menschen darin durchgestrichen. Daneben stehen sie, auf einer Wiese. Du steckst die Zeichnung ein. In Aschenhafen wartet die Stelle, die den Befehl gab. Diesmal wird jemand Fragen stellen.`}
};return ends[s.ending]||null;}
export function hydrate(raw){if(!raw||typeof raw.name!=='string'||raw.version!==VERSION||!CLASSES[raw.role]||!Number.isInteger(raw.area)||raw.area<0||raw.area>3)throw Error('Dieser Spielstand passt nicht zu Teil 1.');const s=fresh(raw.name,raw.role);s.area=raw.area;s.hp=Math.min(CLASSES[s.role].hp,Math.max(1,Number(raw.hp)||1));s.potions=Math.min(2,Math.max(0,Math.floor(Number(raw.potions)||0)));s.trust=Math.min(10,Math.max(-10,Number(raw.trust)||0));s.flags=Object.fromEntries(FLAG_KEYS.filter(k=>raw.flags?.[k]===true).map(k=>[k,true]));s.journal=Array.isArray(raw.journal)?raw.journal.slice(0,60).filter(x=>typeof x.title==='string'&&typeof x.text==='string').map(x=>({title:x.title.slice(0,100),text:x.text.slice(0,2000)})):[];s.rolls=Array.isArray(raw.rolls)?raw.rolls.slice(-20).filter(x=>typeof x==='string').map(x=>x.slice(0,200)):[];s.ending=['release','renew','share'].includes(raw.ending)?raw.ending:null;s.position={x:Math.min(.86,Math.max(.14,Number(raw.position?.x)||.5)),y:Math.min(.9,Math.max(.2,Number(raw.position?.y)||.82))};s.savedAt=raw.savedAt||null;if(raw.storyRevision!==2){s.journal=[];s.recapPending=true;log(s,'Meine Reise','Ich reise allein nach Dornwacht, um Medizin zu liefern. Meine Mutter Runa verschwand vor drei Jahren; ich trage ihre Laterne.');if(s.area>0)log(s,'Das verschwundene Dorf','Die Medizin liegt in der Heilstube. Die Bewohner sind verschwunden, aber eine Stimme ist aus dem Brunnen zu hören.');if(s.flags.ledger)log(s,'Der ursprüngliche Vertrag','Das Leuchtfeuer schützt vor dem Grausturm. Es darf freiwillige Erinnerungen erhalten, aber keine Menschen festhalten. Runas Skizze öffnet den Zugang unter der Kapelle.');if(s.flags.well)log(s,'Die Stimmen','Elin, Lene und die anderen leben im Speicher und können über meine Laterne antworten. Sie haben der Gefangenschaft nicht zugestimmt.');if(s.flags.mural)log(s,'Runas Wartungsplan','Erst lösen, dann abschalten befreit alle ohne Schutz. Eine eigene Erinnerung gewährt sieben Nächte. Vertrag, heutige Antworten und Gegenlaterne erlauben eine freiwillige neue Vereinbarung.');}else s.recapPending=!!raw.recapPending;return s;}
