import {CLASSES,check,log,evidence,startCombat,endingText} from './engine.mjs';
export const AREAS=[
 {name:'Der letzte Weg',sub:'I · AN DER GRENZE',atlas:[0,0],start:[.51,.83],bounds:[.19,.83,.20,.9],hotspots:[{id:'camp',x:.28,y:.56,name:'Weglager',icon:'fire'},{id:'stone',x:.71,y:.46,name:'Grenzstein',icon:'rune'},{id:'gate',x:.56,y:.24,name:'Nach Dornwacht',icon:'arch'}]},
 {name:'Dornwacht',sub:'II · DIE DREIZEHNTE GLOCKE',atlas:[1,0],start:[.49,.84],bounds:[.24,.79,.26,.89],hotspots:[{id:'ledger',x:.28,y:.59,name:'Das Register',icon:'book'},{id:'well',x:.74,y:.47,name:'Der Brunnen',icon:'water'},{id:'bell',x:.50,y:.29,name:'Die Kapelle',icon:'bell'},{id:'back',x:.49,y:.88,name:'Zurück zum Weg',icon:'back'}]},
 {name:'Das Namenarchiv',sub:'III · WAS MARA VERSCHWIEG',atlas:[0,1],start:[.50,.80],bounds:[.21,.79,.27,.84],hotspots:[{id:'mural',x:.26,y:.49,name:'Das Wandbild',icon:'rune'},{id:'mara',x:.72,y:.57,name:'Mit Mara reden',icon:'person'},{id:'guardian',x:.50,y:.29,name:'Der Wächter',icon:'shield'},{id:'back',x:.5,y:.84,name:'Zurück ins Dorf',icon:'back'}]},
 {name:'Die Wurzelkammer',sub:'IV · DEIN VERSPRECHEN',atlas:[1,1],start:[.50,.82],bounds:[.23,.78,.28,.86],hotspots:[{id:'core',x:.50,y:.46,name:'Das Leuchtfeuer',icon:'sun'},{id:'mara',x:.28,y:.67,name:'Mara',icon:'person'},{id:'back',x:.50,y:.86,name:'Zurück ins Archiv',icon:'back'}]}
];
const c=(label,next,extra={})=>({label,next,...extra});
const n=(speaker,title,text,choices)=>({speaker,title,text,choices});
const close=c('Weiter erkunden',null);
export function objective(s){if(s.ending)return 'Dein erster Weg ist zu Ende. Ein neuer beginnt.';if(s.area===0)return s.flags.iven?'Erkunde den Weg und erreiche Dornwacht.':'Finde heraus, wer am Weglager Hilfe braucht.';if(s.area===1)return s.flags.ledger?'Untersuche den Brunnen oder öffne die Kapelle.':'Suche im verlassenen Dorf nach einem Hinweis.';if(s.area===2)return s.flags.guardian?'Der Weg zum Leuchtfeuer ist frei.':'Finde die Wahrheit über den Vertrag und den Wächter.';return 'Höre die Eingeschlossenen. Entscheide über den Schutz.';}
export function getNode(s,id){const f=s.flags;const nodes={
 intro:()=>n('Mara','Nicht jeder Weg beginnt mit Mut',`Der Morgen riecht nach nassem Holz. Zum ersten Mal liegt dein Heimatdorf hinter dir, ${s.name}. In deinem Rucksack klirren zwei Heiltränke gegen das Medizinpäckchen für Dornwacht. Die Bestellung trägt das Siegel des Dorfrats und ist drei Tage alt.\n\nMara wartet am Grenzstein. „Deine Mutter hat diese Laterne nie aus der Hand gegeben.“ Sie sieht weg. „Es ist nicht weit. Wir bringen die Medizin hin und kehren um.“`,[c('„Du hast meine Mutter gekannt?“','introMother'),c('„Dann gehen wir.“',null,{flags:['intro']})]),
 introMother:()=>n('Mara','Eine sorgfältige Antwort','„Wir sind denselben Weg gegangen. Früher.“ Sie prüft den Verschluss ihres Mantels, obwohl er längst geschlossen ist.\n\n„Unterwegs erzähle ich dir mehr. Und wenn du etwas versuchen willst: Ich zeige dir, wie du deine Chancen einschätzt.“',[c('Mit Mara aufbrechen',null,{flags:['intro'],note:['Der Auftrag','Medizin nach Dornwacht bringen. Die Bestellung ist drei Tage alt. Mara kannte meine verschwundene Mutter Runa.']})]),
 camp:()=>f.iven?n('Iven','Ein Feuer hält Wache',f.medicineGiven?'Iven hält das leere Medizinpapier zwischen den Fingern. „Ich folge euch, sobald meine Beine wieder mitmachen. Die Leute im Dorf brauchen diese Medizin trotzdem. Gut, dass noch etwas übrig ist.“':f.ivenSaved?'Iven tastet nach deinem Verband. „Ich bleibe noch einen Moment. Dann komme ich nach. Und wenn sie sagen, jeder hätte zugestimmt: Fragt sie nach den Kindern.“':'Iven sitzt dicht am Feuer. „Ich bleibe hier, bis jemand mit einem Verband zurückkommt. Im Dorf war ich nicht willkommen, als ich Fragen gestellt habe.“',[close]):n('Iven · ein Bote','Der Mann neben dem Feuer','Ein junger Bote sitzt mit aufgerissener Wade am Feuer. Seine Tasche ist mit grauem Staub bedeckt.\n\n„Die Glocke schlug dreizehnmal. Heute Morgen. Dann wurde der Platz leer.“ Er hält dir ein zerrissenes Blatt hin. „Ich sollte nur den Vertrag verlängern. Ich habe nicht gewusst, was ‚vollständige Deckung‘ bedeutet.“',[c('Medizin teilen und die Wunde versorgen','ivenSaved',{flags:['iven','medicineGiven','ivenSaved'],trust:1,note:['Ivens Auftrag','Der Bote brachte heute Morgen eine Vertragsverlängerung. Beim dreizehnten Glockenschlag verschwanden die Bewohner. Ein Teil unserer Medizin bleibt für das Dorf.']}),c('Mit Stoff verbinden · Heilkunde','ivenBandage',{test:{skill:'medicine',dc:11},once:'iven'}),c('Erst nach dem Blatt fragen','ivenLetter')]),
 ivenLetter:()=>n('Iven','Vollständige Deckung','Auf dem Papier steht: „Bei erschöpfter Erinnerungsreserve wird das Pfand vollständig eingezogen.“ Darunter ein alter Stempel, aber keine neue Unterschrift.\n\n„Der Wächter sagte, die Zustimmung sei schon vorhanden.“ Iven lacht ohne Freude. „Ich bin Bote. Das ist keine Entschuldigung. Es ist nur das, was ich mir gesagt habe.“',[c('Medizin mit ihm teilen','ivenSaved',{flags:['iven','medicineGiven','ivenSaved'],trust:1,note:['Das eingezogene Pfand','Die Vertragsverlängerung verlangt bei leerer Erinnerungsreserve ein vollständiges Pfand. Eine neue Unterschrift fehlt.']}),c('Zumindest einen Verband versuchen','ivenBandage',{test:{skill:'medicine',dc:11},once:'iven'}),c('„Ich gehe der Sache nach.“',null,{flags:['iven'],note:['Der Bote am Weg','Iven überbrachte unwissentlich eine gefährliche Vertragsverlängerung. Er wartet verletzt am Feuer.']})]),
 ivenSaved:()=>n('Mara','Die erste Entscheidung','Ivens Atem wird ruhiger. Du gibst ihm einen Teil des Medizinpäckchens. Die beiden Heiltränke in deinem Rucksack bleiben unangetastet.\n\nMara kniet neben dir. „Manchmal brauchst du keinen Würfel. Wenn du etwas sicher kannst und nichts dagegensteht, tust du es einfach.“',[close]),
 ivenBandage:()=>n('Mara','Was ein Wurf bedeutet',f.ivenSaved?'Dein Verband hält. Iven kann den Fuß wieder aufsetzen.\n\n„Der W20 zeigt die Ungewissheit“, sagt Mara. „Deine Übung kommt dazu. Zusammen muss es mindestens die Schwierigkeit erreichen.“':'Der Stoff hält die Blutung auf, aber Iven kann nicht laufen. Am Feuer ist er vorerst sicher.\n\nMara reicht ihm Wasser. „Ein Fehlschlag heißt nicht, dass du nichts bewirkt hast. Nur, dass es anders weitergeht.“',[close]),
 stone:()=>f.inscription?n('Deine Laterne','Eine Zeile im Stein','„Kein Schutz ohne Namen. Kein Name ohne Antwort.“\n\nDas Wort Antwort ist tiefer eingeschnitten als die anderen. Als hätte jemand darauf bestanden.',[close]):n('Mara','Was der Regen nicht auswäscht','Zwischen Moos und Wurzeln erkennst du eine Inschrift. Die Laterne wird warm, obwohl ihre Flamme nicht brennt.\n\nMara hält dir den Zweig aus dem Licht. „Ich helfe dir beim Lesen. Zwei W20, der höhere zählt. Das nennen wir Vorteil.“',[c('Inschrift entziffern · Nachforschungen','stoneRead',{test:{skill:'investigation',dc:12,advantage:true},once:'inscription'}),close]),
 stoneRead:()=>n('Deine Laterne','Kein Name ohne Antwort','„Kein Schutz ohne Namen. Kein Name ohne Antwort.“\n\nDu zeichnest die Worte ab. Selbst wo du die Schrift nicht lesen konntest, zeichnete das Licht die Buchstaben nach. Die genauere Deutung hängt davon ab, wie gut dir die Probe gelang.\n\nMara berührt das Wort Antwort. „Merkwürdig, was man irgendwann zu überlesen lernt.“',[close]),
 gate:()=>f.bridge?n('Mara','Dornwacht liegt dahinter','Jenseits des Torbogens hängt Nebel zwischen den Häusern. Ein Glockenseil bewegt sich, obwohl kein Wind geht.',[c('Nach Dornwacht', 'villageIntro',{area:1}),close]):n('Mara','Ein Schritt über das Wasser','Vor dem Tor ist ein Teil des Stegs fortgespült. Das Wasser darunter ist flach, aber schnell.\n\nDu könntest springen. Oder das Seil aus Maras Gepäck um den alten Pfeiler legen. „Wir haben Zeit“, sagt sie. „Nicht jede Gefahr ist eine Prüfung, die du bestehen musst.“',[c('Mit Maras Seil sichern','crossSafe',{flags:['bridge','rope'],note:['Mit Bedacht','Den zerstörten Steg mit einem Seil überwunden. Gute Vorbereitung kann eine Probe überflüssig machen.']}),c('Über die Lücke springen · Athletik','crossJump',{test:{skill:'athletics',dc:12},once:'bridge'}),close]),
 crossSafe:()=>n('Mara','Ein verlässlicher Knoten','Das Seil hält. Mara folgt dir über den Steg. Hinter euch zieht sich eine feine goldene Linie durch den Nebel, als hätte die Laterne den Weg behalten.',[c('Das Dorf betreten','villageIntro',{area:1})]),
 crossJump:()=>n('Mara','Am anderen Ufer',s._lastSuccess?'Deine Stiefel finden festen Stein. Mara kommt mit dem Seil nach. „Gut. Und nächstes Mal überlegst du trotzdem wieder, ob du springen musst.“':'Dein Fuß rutscht am Rand ab. Mara fängt dich am Riemen. Du schlägst das Knie an, verlierst 2 Lebenspunkte und kommst mit dem Seil hinüber. Der Weg bleibt offen.',[c('Weiter nach Dornwacht','villageIntro',{area:1})]),
 villageIntro:()=>n('Dornwacht','Die Suppe ist noch warm','Auf dem Dorfplatz steht ein Wagen mit frischem Brot. Eine Tür schlägt gegen den Rahmen. Du legst die übrige Medizin auf den Tisch der Heilstube und rufst. Niemand antwortet.\n\nDann hörst du aus dem Brunnen: „Ist schon Abend?“\n\nMara wird blass. „Nein. Das hätte nicht passieren dürfen.“',[c('Den Platz erkunden',null,{flags:['villageIntro'],note:['Ein frisches Verschwinden','Das Dorf verschwand heute Morgen, nicht vor Jahren. Die Heilstube hat unsere restliche Medizin. Stimmen kommen aus dem Brunnen.']})]),
 ledger:()=>f.ledger?n('Das Dorfbuch','Siebzehn Jahre, ein falsches Wort','Der ursprüngliche Vertrag verlangt Erinnerungen – niemals Menschen. Die Verlängerung wurde vom Wächter eigenmächtig ausgelegt. Die Liste enthält die Namen der damals zustimmenden Erwachsenen. Die Kinder von heute stehen nicht darin.',[close]):n('Das Dorfbuch','Was unterschrieben wurde','Auf dem Tisch liegt ein Register, aufgeschlagen neben einem noch feuchten Stempel.\n\nVor siebzehn Jahren schützte ein Leuchtfeuer das Dorf vor dem Grausturm. Einmal im Jahr gaben die erwachsenen Unterzeichner eine Erinnerung ab. Heute hat der Wächter „Erinnerung“ durch „Träger der Erinnerung“ ersetzt.\n\nIn einer Randnotiz deiner Mutter steht: „Ein Vertrag kann nur von denen erneuert werden, die er betrifft.“',[c('Namen und Wortlaut abschreiben',null,{flags:['ledger'],note:['Beweis I · Der ursprüngliche Vertrag','Der Vertrag erlaubt Erinnerungen, niemals Menschen. Nur damals zustimmende Erwachsene unterschrieben. Runa verlangt für jede Erneuerung eine neue Antwort.']})]),
 well:()=>f.well?n('Elin · aus dem Brunnen','Die Menschen hinter dem Echo','„Wir hören dich noch“, sagt Elin. „Wenn du eine Tür findest: Frag uns. Entscheide nicht wieder für uns.“',[close]):n('Elin · aus dem Brunnen','Kein Geist','Du beugst dich über den Rand. Eine Frau antwortet aus einer Tiefe, die unmöglich im Brunnen liegen kann. „Ich heiße Elin. Meine Tochter ist hier. Sie ist sechs.“\n\nDie Laterne wirft ein Gesicht auf das Wasser. „Wir sind keine Toten. Es fühlt sich an, als halte jemand einen Atemzug fest.“',[c('„Habt ihr dem zugestimmt?“','wellConsent'),c('„Ich bringe euch zurück.“','wellPromise')]),
 wellConsent:()=>n('Elin','Eine Antwort ist keine Erbschaft','„Damals wollte ich meine Familie schützen. Ich wusste, dass ich etwas vergessen würde. Aber meine Tochter hat nie etwas versprochen.“\n\nDu bittest sie, weitere Namen zu nennen. Die Laterne wiederholt jeden wie einen leisen Ton. Die Eingeschlossenen können antworten, solange ihr Licht sie erreicht.',[c('Die Antworten festhalten',null,{flags:['well'],trust:1,note:['Beweis II · Die Stimmen','Elin und ihre Tochter leben im Speicher des Leuchtfeuers. Die Laterne kann sie ansprechen. Kinder haben nie zugestimmt; Zustimmung wird nicht vererbt.']})]),
 wellPromise:()=>n('Elin','Ein großes Wort','„Sag nicht etwas, nur weil es mich beruhigt.“ Du hörst ein Kind husten. „Frag lieber, was wir brauchen.“\n\nDu setzt dich an den Rand und hörst zu. Nach einer Weile nennt Elin die Namen der anderen. Die Laterne antwortet mit Licht.',[c('Zuhören und Namen notieren',null,{flags:['well'],note:['Beweis II · Die Stimmen','Die Eingeschlossenen leben und können über die Laterne antworten. Elin bittet um eine eigene Entscheidung, nicht um ein fremdes Versprechen.']})]),
 bell:()=>!f.ledger?n('Mara','Das Siegel an der Kapelle','In der Tür steht: „Nur wer den Vertrag kennt, darf ihn auslegen.“\n\n„Das Dorfbuch liegt gegenüber“, sagt Mara. „Wenn wir nicht wissen, was versprochen wurde, machen wir vielleicht denselben Fehler.“',[close]):n('Mara','Unter der dreizehnten Glocke','Die Namen aus dem Register lassen deine Laterne aufleuchten. Unter dem Glockenturm öffnet sich eine Treppe.\n\nMara zieht einen alten Schlüssel hervor. Genau denselben, der am Rand des Registers abgebildet ist. „Ich wollte, dass du es von mir erfährst“, sagt sie.\n\nDu lässt die Worte einen Moment stehen.',[c('Mit ihr hinabsteigen','archiveIntro',{flags:['bell'],area:2}),close]),
 archiveIntro:()=>n('Das Namenarchiv','Aufbewahren ist nicht dasselbe wie bewahren','In Nischen stehen Glasplatten, jede mit einem Namen. Licht fließt in den Boden. Weiter hinten hebt eine Gestalt aus Holz und Metall den Kopf.\n\n„Vertrag erfüllt. Schutz aufrechterhalten.“\n\nMara flüstert: „Er kann nicht lügen. Aber er kann sich irren.“',[c('Das Archiv untersuchen',null,{flags:['archiveIntro']})]),
 mural:()=>f.mural?n('Runas Aufzeichnung','Drei fehlende Teile','Die Randzeichnung verbindet drei Dinge: ursprüngliche Namen, gegenwärtige Antworten, ein Gegenzeichen. Das Gegenzeichen ist in deiner Laterne. Erst gemeinsam öffnen sie einen neuen Vertrag.',[close]):n('Runas Aufzeichnung','Deine Mutter hat einen Weg hinterlassen','Auf einer Glasplatte erkennst du Runas Handschrift:\n\n„Ein Wächter ohne Zweifel wird jedes Unrecht für eine Pflicht halten. Der Kern lässt sich abschalten. Eine freiwillige Erinnerung kann ihn sieben Nächte tragen. Ein neuer Vertrag braucht drei Dinge: Namen, lebendige Antworten und mein Gegenzeichen.“\n\nDarunter ist deine Laterne gezeichnet. Kein Schlüssel zur Macht. Ein Recht, eine Entscheidung neu zu öffnen.',[c('Das Gegenzeichen mit der Laterne vergleichen',null,{flags:['mural'],note:['Beweis III · Das Gegenzeichen','Runas Laterne erlaubt einen neuen Vertrag: Namen aus dem Register + Antworten der Eingeschlossenen + Gegenzeichen. Abschalten befreit alle, beendet aber den Schutz. Eine Erinnerung kauft genau sieben Nächte.']})]),
 mara:()=>f.confession?n('Mara','Was nach einer Wahrheit bleibt',f.forgiven?'„Du musst mir nicht jeden Tag verzeihen“, sagt Mara. „Sag mir nur, wenn ich wieder anfange, für dich zu entscheiden.“':'Mara hält deinen Blick. „Ich bleibe. Nicht, weil du mir etwas schuldest. Weil ich dir etwas schulde.“',[c('Eine kurze Rast einlegen','rest',{rest:true,disabled:!!f.rested}),close]):n('Mara','Die Unterschrift unter dem Schweigen','„Ich war die Wegwächterin. Ich habe die Menschen zum Unterschreiben gebracht.“\n\nSie nimmt die Handschuhe ab. „Der Sturm war real. Die Alternative war damals nicht einfach. Aber als Runa entdeckte, dass die Erinnerungen weniger wurden, wollte sie den Vertrag öffnen. Ich hielt das für zu gefährlich. Ich habe ihr den Weg versperrt.“\n\n„Sie ging allein zum nächsten Leuchtfeuer. Seitdem fehlt sie. Ich habe dir erzählt, ich hätte sie kaum gekannt. Das war eine Lüge.“',[c('„Ich verstehe deine Angst. Die Lüge bleibt.“','maraAfter',{flags:['confession','forgiven'],trust:2}),c('„Hilf mir jetzt. Vertrauen kommt später.“','maraAfter',{flags:['confession'],trust:-1}),c('„Du entscheidest nie wieder für mich.“','maraAfter',{flags:['confession'],trust:-2})]),
 maraAfter:()=>n('Mara','Kein Freispruch','„Ja.“ Kein Aber, kein neuer Grund. Nur dieses eine Wort.\n\nSie gibt dir ihren Wegwächterschlüssel. „Das Gegenzeichen konnte Runa nicht mitnehmen, ohne den Wächter zu warnen. Deshalb blieb die Laterne bei dir. Ich weiß nicht, ob sie noch lebt. Wer dir etwas anderes verspricht, weiß weniger, als er behauptet.“',[c('Den Schlüssel annehmen',null,{note:['Maras Geständnis','Mara war Wegwächterin und verhinderte Runas Reformversuch. Runa ging daraufhin zum nächsten Leuchtfeuer. Ihr Schicksal ist unbekannt. Die Laterne blieb absichtlich bei mir.']})]),
 rest:()=>n('Mara','Ein Atemzug zwischen den Dingen','Ihr setzt euch an eine warme Steinplatte. Mara teilt Brot und Wasser. Deine Wunden beruhigen sich.\n\nFür dieses Einführungsabenteuer heilt diese einmalige Rast vollständig. Das ist eine vereinfachte Rastregel.',[close]),
 guardian:()=>f.guardian?n('Das innere Tor','Der Weg liegt offen',f.guardianPeace?'Der Wächter tritt zur Seite. „Vertragsprüfung läuft. Ich werde warten.“':'Die hölzerne Gestalt liegt still. Im Kern arbeitet das Leuchtfeuer weiter.',[c('Die Wurzelkammer betreten','sanctumIntro',{area:3}),close]):n('Der Wächter','„Das Dorf ist geschützt.“','Die Gestalt blockiert den Durchgang. Zwischen ihren Rippen bewegt sich goldenes Licht.\n\n„Auftrag: Dornwacht erhalten. Menschen außerhalb des Speichers gefährdet. Menschen im Speicher erhalten. Auftrag erfüllt.“\n\nMara stellt sich neben dich. „Du kannst gegen ihn kämpfen. Oder ihm zeigen, wo seine Auslegung dem Vertrag widerspricht.“',[c('Den Widerspruch beweisen','guardianProof',{disabled:evidence(s)<2,hint:'Zwei Beweise nötig'}),c('Eine Prüfung verlangen · Überreden','guardianTalk',{test:{skill:'persuasion',dc:14},once:'guardianAttempt',disabled:!!f.guardianTried,hint:'Bereits versucht – sammle Beweise oder kämpfe'}),c('Den Durchgang freikämpfen',null,{combat:true}),close]),
 guardianProof:()=>n('Der Wächter','Ein Zweifel im Holz','Du legst den ursprünglichen Wortlaut neben Runas Aufzeichnung oder Elins Antwort. „Schutz erlaubt kein neues Pfand. Und ohne Antwort gibt es keinen neuen Vertrag.“\n\nLange bewegt sich nichts. Dann senkt der Wächter den Arm. „Widerspruch festgestellt. Prüfung durch Gegenzeichner erforderlich.“',[c('Die Prüfung übernehmen',null,{flags:['guardian','guardianPeace'],note:['Ein Wächter lernt Zweifel','Mit zwei unabhängigen Beweisen wurde der Widerspruch im Vertrag nachgewiesen. Der Wächter ließ uns friedlich passieren.']})]),
 guardianTalk:()=>s._lastSuccess?n('Der Wächter','„Prüfung gestattet.“','Du erklärst, dass du den Auftrag nicht beenden, sondern überprüfen willst. Die Laterne bestätigt deine Berechtigung. Der Wächter gibt den Weg frei.',[c('Die Laterne heben',null,{flags:['guardian','guardianPeace']})]):n('Mara','Eine andere Sprache','Der Wächter weicht nicht. „Behauptung nicht ausreichend.“\n\nMara flüstert: „Dann brauchen wir Beweise. Das Register und eine zweite Quelle. Oder wir kämpfen.“',[close]),
 sanctumIntro:()=>n('Die Wurzelkammer','Viele Atemzüge, ein Licht','Über den Wurzeln schweben hunderte winzige Lichtpunkte. Keine Seelen. Menschen, deren Gegenwart angehalten wurde. Du hörst eine Mutter ihr Kind beruhigen.\n\nDie Laterne in deiner Hand antwortet. Auf dem Ring vor dir erscheinen zwei sichere Wege. Ein dritter bleibt blass, solange du seine Bedingungen nicht zusammengetragen hast.',[c('Zum Leuchtfeuer gehen',null,{flags:['sanctumIntro']})]),
 core:()=>n('Das Leuchtfeuer','Wer darf für andere entscheiden?',`Du kannst den Kern abschalten: Alle kommen zurück, aber der Schutz vor dem nächsten Grausturm fällt.\n\nDu kannst freiwillig eine prägende Erinnerung geben: Alle kommen zurück, der Schutz hält noch sieben Nächte. Danach muss eine andere Lösung gefunden sein.\n\n${evidence(s)===3?'Du hast alle drei Beweise. Mit der Laterne kannst du die Menschen selbst nach einem neuen Vertrag fragen. Wer ablehnt, wird trotzdem befreit. Der Schutz wird schwächer, aber freiwillig.':'Runas dritter Weg ist noch unvollständig. Du kannst jederzeit zurückgehen und Register, Brunnen und Wandbild untersuchen.'}`,[c('Abschalten · Freiheit ohne Schutz','confirmRelease'),c('Meine Erinnerung geben · sieben Nächte','confirmRenew'),c('Die Menschen selbst entscheiden lassen','confirmShare',{disabled:evidence(s)<3,hint:'Register, Brunnen und Wandbild nötig'}),c('Ich brauche noch Zeit',null)]),
 confirmRelease:()=>n('Mara','Ein Morgen ohne Gewissheit','„Wenn du den Kern löschst, endet der alte Vertrag. Wir müssen mit den Zurückgekehrten einen neuen Schutz finden.“\n\nDie Laterne zeigt dir eine Straße ohne Nebel. Dahinter Wolken. Du rettest die Menschen heute. Du versprichst ihnen keine sichere Zukunft.',[c('Den Kern endgültig löschen','ending',{ending:'release'}),c('Noch nicht','core')]),
 confirmRenew:()=>n('Deine Erinnerung','Der Preis hat einen Namen','Der Kern zeigt dir einen Abend aus deiner Kindheit. Deine Mutter sitzt an deinem Bett und singt.\n\nEr verlangt nicht dein Wissen über sie, nicht dein Gesicht für sie, sondern ihre Stimme. Genau diese Erinnerung. Du gibst sie freiwillig für sieben Nächte. Es gibt keine versteckte Verlängerung.',[c('Ihre Stimme loslassen','ending',{ending:'renew'}),c('Diese Erinnerung behalten','core')]),
 confirmShare:()=>n('Elin und die anderen','Eine Antwort nach der anderen','Du liest die Namen. Die Laterne trägt die Frage in den Speicher. Keine Stimme wird übertönt.\n\nEinige wollen den Schutz erneuern. Andere nicht. Du änderst den Vertrag so, dass eine Ablehnung niemals die Rückkehr verhindert. Die Zustimmenden geben kleine Erinnerungen; für einen schwächeren Schutz, den sie jedes Jahr neu wählen müssen.',[c('Den neuen Vertrag gegenzeichnen','ending',{ending:'share'}),c('Noch einmal nachdenken','core')]),
 ending:()=>{const e=endingText(s);return n(e.kicker,e.title,e.text+'\n\n'+e.hook,[c('Den Epilog schließen',null)]);},
 back:()=>n('Mara','Der Weg bleibt offen','Ihr könnt zurückgehen. Hinweise und getroffene Entscheidungen bleiben erhalten.',[c('Zurückgehen',null,{area:Math.max(0,s.area-1)}),close])
 };return (nodes[id]||(()=>n('Mara','Ein Moment','Wir sollten uns weiter umsehen.',[close])))();}
export function applyChoice(s,choice,dice=[]){if(s.ending)return {node:'ending'};if(choice.disabled)return {node:null};if(choice.test){const t=choice.test,r=check(s,t.skill,t.dc,dice[0],t.advantage?dice[1]:null);s._lastSuccess=r.success;s.rolls.push(`${r.dice.join(' / ')} + ${r.bonus} = ${r.total} gegen ${r.dc}: ${r.success?'Erfolg':'Fehlschlag'}`);s.rolls=s.rolls.slice(-20);if(choice.once==='guardianAttempt')s.flags.guardianTried=true;if(choice.once==='iven'){s.flags.iven=true;if(r.success)s.flags.ivenSaved=true;log(s,'Die erste Probe',r.success?'Iven ist verbunden und kann später folgen.':'Iven ist stabil, bleibt aber vorerst am Feuer.');}if(choice.once==='bridge'){s.flags.bridge=true;if(!r.success)s.hp=Math.max(1,s.hp-2);}if(choice.once==='inscription'){s.flags.inscription=true;log(s,'Kein Name ohne Antwort',r.success?'Die Inschrift verlangt ausdrücklich eine Antwort jeder betroffenen Person.':'Die Laterne zeichnet die Worte nach: Kein Schutz ohne Namen. Kein Name ohne Antwort.');}}
for(const k of choice.flags||[])s.flags[k]=true;if(choice.trust)s.trust+=choice.trust;if(choice.note)log(s,...choice.note);if(choice.area!==undefined){s.area=choice.area;const [x,y]=AREAS[s.area].start;s.position={x,y};}if(choice.rest&&!s.flags.rested){s.flags.rested=true;s.hp=CLASSES[s.role].hp;}if(choice.combat)startCombat(s);if(choice.ending){if(choice.ending==='share'&&evidence(s)<3)throw Error('Der neue Vertrag benötigt alle drei Beweise.');s.ending=choice.ending;s.flags.end=true;log(s,'Dein Vermächtnis',endingText(s).title);}return {node:choice.next};}
