import {AREAS} from './story.mjs';
export function walkable(area,x,y){const [l,r,t,b]=AREAS[area].bounds;if(x<l||x>r||y<t||y>b)return false;if(area===0){const center=.51+Math.sin(y*5)*.035;return Math.abs(x-center)<(y>.42&&y<.65?.30:.155);}if(area===2)return ((x-.5)/.32)**2+((y-.55)/.34)**2<1.08;if(area===3)return ((x-.5)/.29)**2+((y-.56)/.32)**2<1.04;return true;}
export function findPath(area,start,end){const N=40;const point=p=>({x:Math.round(p.x*N),y:Math.round(p.y*N)});const key=(x,y)=>y*(N+1)+x;let a=point(start),b=point(end);const valid=(x,y)=>walkable(area,x/N,y/N);if(!valid(b.x,b.y))return [];if(!valid(a.x,a.y)){a=point({x:.5,y:.7});}const q=[a],prev=new Map([[key(a.x,a.y),null]]);let found=false;for(let i=0;i<q.length;i++){const p=q[i];if(p.x===b.x&&p.y===b.y){found=true;break;}for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,1],[1,-1],[-1,-1]]){const x=p.x+dx,y=p.y+dy,k=key(x,y);if(valid(x,y)&&!prev.has(k)&&(!dx||!dy||(valid(p.x+dx,p.y)&&valid(p.x,p.y+dy)))){prev.set(k,p);q.push({x,y});}}}if(!found)return [];const path=[];let at=b;while(at){path.push({x:at.x/N,y:at.y/N});at=prev.get(key(at.x,at.y));}return path.reverse().slice(1);}
export class World{
 constructor(canvas,getState,onArrive,onBlocked){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.getState=getState;this.onArrive=onArrive;this.onBlocked=onBlocked;this.art=new Image();this.art.src='assets/worlds.webp';this.hero={x:.5,y:.82};this.mara={x:.43,y:.87};this.path=[];this.target=null;this.time=0;this.last=0;this.active=false;this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this.imageFailed=false;this.art.onerror=()=>{this.imageFailed=true;onBlocked('Die Bildwelt konnte nicht geladen werden. Bitte lade die Seite neu.');};new ResizeObserver(()=>this.resize()).observe(canvas);canvas.addEventListener('pointerup',e=>this.tap(e));this.tick=this.tick.bind(this);requestAnimationFrame(this.tick);}
 resize(){const r=this.canvas.getBoundingClientRect();this.w=r.width;this.h=r.height;const dpr=Math.min(devicePixelRatio||1,2);this.canvas.width=Math.round(r.width*dpr);this.canvas.height=Math.round(r.height*dpr);this.ctx.setTransform(dpr,0,0,dpr,0,0);}
 sync(){const s=this.getState();this.hero={...s.position};this.mara={x:this.hero.x-.07,y:this.hero.y+.035};this.path=[];this.target=null;this.active=true;this.resize();}
 tap(e){if(!this.active||document.querySelector('dialog[open]'))return;const r=this.canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;const a=AREAS[this.getState().area];const hot=a.hotspots.find(h=>Math.hypot((h.x-x)*r.width,(h.y-y)*r.height)<30);if(hot)this.go(hot);else this.go({x,y});}
 go(to){if(!this.active)return;const area=this.getState().area;let dest={x:to.x,y:to.y+(to.id&&to.id!=='back'?.075:0)};if(!walkable(area,dest.x,dest.y)){// Find a nearby accessible standing point for an object.
 if(!to.id){this.onBlocked('Dort ist der Weg versperrt.');return;}let best=null;for(let x=.15;x<.9;x+=.025)for(let y=.2;y<.91;y+=.025)if(walkable(area,x,y)){const dist=Math.hypot(x-to.x,y-to.y);if(!best||dist<best.dist)best={x,y,dist};}dest=best;}
 const path=findPath(area,this.hero,dest);if(!path.length&&Math.hypot(this.hero.x-dest.x,this.hero.y-dest.y)>.05){this.onBlocked('Dieser Weg ist nicht erreichbar.');return;}this.path=path;this.target=to.id?to:null;this.destination=dest;if(!path.length&&this.target){const target=this.target;this.target=null;this.onArrive(target.id);}}
 tick(ts){const dt=Math.min((ts-this.last)/1000||0,.045);this.last=ts;if(this.active&&!document.hidden){this.time+=dt;if(this.path.length&&!document.querySelector('dialog[open]')){const p=this.path[0],dx=p.x-this.hero.x,dy=p.y-this.hero.y,len=Math.hypot(dx,dy),step=dt*.24;if(len<=step){this.hero={...p};this.path.shift();if(!this.path.length){const s=this.getState();s.position={...this.hero};const target=this.target;this.target=null;if(target)this.onArrive(target.id);else this.onArrive(null);}}else{this.hero.x+=dx/len*step;this.hero.y+=dy/len*step;}}const dx=this.hero.x-.065-this.mara.x,dy=this.hero.y+.035-this.mara.y;this.mara.x+=dx*Math.min(1,dt*3);this.mara.y+=dy*Math.min(1,dt*3);this.draw();}requestAnimationFrame(this.tick);}
 draw(){const c=this.ctx,w=this.w,h=this.h;if(!w||!h)return;const s=this.getState(),a=AREAS[s.area];c.clearRect(0,0,w,h);if(this.art.complete&&this.art.naturalWidth){const size=this.art.naturalWidth/2;c.drawImage(this.art,a.atlas[0]*size,a.atlas[1]*size,size,size,0,0,w,h);}else{c.fillStyle='#203b3a';c.fillRect(0,0,w,h);}c.fillStyle='rgba(10,27,31,.13)';c.fillRect(0,0,w,h);
 if(this.path.length){c.beginPath();c.moveTo(this.hero.x*w,this.hero.y*h);for(const p of this.path)c.lineTo(p.x*w,p.y*h);c.strokeStyle='#f6d89570';c.lineWidth=1.5;c.setLineDash([2,6]);c.stroke();c.setLineDash([]);const p=this.path.at(-1);c.strokeStyle='#f6d895';c.beginPath();c.ellipse(p.x*w,p.y*h,9,4,0,0,Math.PI*2);c.stroke();}
 for(const hot of a.hotspots){const x=hot.x*w,y=hot.y*h;const done=s.flags[hot.id]||(hot.id==='camp'&&s.flags.iven)||(hot.id==='stone'&&s.flags.inscription)||(hot.id==='mara'&&s.flags.confession);c.beginPath();c.arc(x,y,17,0,Math.PI*2);c.fillStyle=done?'#13282cc2':'#122a30e0';c.fill();c.strokeStyle=done?'#9ab3a16b':'#e4c681ba';c.lineWidth=1;c.stroke();c.fillStyle=done?'#a4b9a5':'#edcf90';c.font='18px Georgia';c.textAlign='center';c.textBaseline='middle';const glyph={fire:'♨',rune:'◇',arch:'⌃',book:'≡',water:'≈',bell:'♧',person:'✧',shield:'♜',sun:'☼',back:'⌄'}[hot.icon];c.fillText(glyph,x,y);c.font='9px system-ui';const tw=c.measureText(hot.name).width;c.fillStyle='#0b1f26db';c.beginPath();c.roundRect(x-tw/2-7,y+21,tw+14,19,4);c.fill();c.fillStyle='#e5e5ce';c.fillText(hot.name,x,y+30);}
 if(s.combat){this.person({x:.5,y:.32},false,false);c.fillStyle='#e3b885';c.font='11px system-ui';c.textAlign='center';c.fillText('Wächter · '+s.combat.hp+' LP',w*.5,h*.32-44);}
 const moving=this.path.length>0;const actors=[{p:this.hero,hero:true},{p:this.mara,hero:false}].sort((a,b)=>a.p.y-b.p.y);for(const a of actors)this.person(a.p,a.hero,moving);
 if(!this.reduced){for(let i=0;i<20;i++){const x=((i*.137+this.time*.004)%1)*w,y=((i*.193+Math.sin(this.time*.3+i)*.015)%1)*h;c.globalAlpha=.2+.35*Math.max(0,Math.sin(this.time+i));c.fillStyle=i%3?'#ddd99a':'#83c9bd';c.beginPath();c.arc(x,y,i%3?1:1.5,0,Math.PI*2);c.fill();}c.globalAlpha=1;const fog=c.createLinearGradient(0,h*.5,w,h*.7);fog.addColorStop(0,'#abddd000');fog.addColorStop(.5,'#adccc50b');fog.addColorStop(1,'#abddd000');c.fillStyle=fog;c.fillRect(0,h*(.55+Math.sin(this.time*.15)*.05),w,h*.18);}}
 person(p,hero,moving){const c=this.ctx,x=p.x*this.w,y=p.y*this.h;const scale=Math.max(.85,Math.min(1.4,this.w/390));c.save();c.translate(x,y);c.scale(scale,scale);const bob=moving&&!this.reduced?Math.sin(this.time*13+(hero?0:1))*1.2:0;c.fillStyle='#0007';c.beginPath();c.ellipse(0,2,11,4,0,0,7);c.fill();if(hero){const glow=c.createRadialGradient(9,-10,0,9,-10,45);glow.addColorStop(0,'#ffd58642');glow.addColorStop(1,'#ffc16c00');c.fillStyle=glow;c.fillRect(-40,-55,90,90);}c.translate(0,bob);c.strokeStyle='#302d27';c.lineWidth=4;c.beginPath();c.moveTo(-4,-6);c.lineTo(-4+(moving?Math.sin(this.time*13)*2:0),1);c.moveTo(4,-6);c.lineTo(4-(moving?Math.sin(this.time*13)*2:0),1);c.stroke();const cloak=c.createLinearGradient(-9,-20,9,0);cloak.addColorStop(0,hero?'#466f66':'#71717b');cloak.addColorStop(1,hero?'#1d413e':'#363e4b');c.fillStyle=cloak;c.beginPath();c.moveTo(-5,-22);c.quadraticCurveTo(-9,-12,-11,-4);c.quadraticCurveTo(0,1,10,-4);c.lineTo(5,-23);c.closePath();c.fill();c.strokeStyle=hero?'#bda573':'#99acb2';c.lineWidth=1;c.beginPath();c.moveTo(0,-20);c.lineTo(2,-5);c.stroke();c.fillStyle=hero?'#3c5f55':'#59646a';c.beginPath();c.ellipse(0,-24,6,7,0,0,7);c.fill();c.fillStyle='#d3b792';c.beginPath();c.ellipse(1,-23,3.3,4,0,0,7);c.fill();c.fillStyle='#293632';c.beginPath();c.arc(0,-26,5,Math.PI,Math.PI*2);c.fill();if(hero){c.strokeStyle='#a18953';c.strokeRect(9,-14,5,7);c.fillStyle='#ffe4a2';c.fillRect(10,-13,3,5);}else{c.strokeStyle='#8f8063';c.lineWidth=2;c.beginPath();c.moveTo(-10,-20);c.lineTo(-12,1);c.stroke();}c.restore();}
}
