import test from 'node:test';
import assert from 'node:assert/strict';
import {fresh,check,hydrate,evidence,combatAction,startCombat,CLASSES,endingText} from '../engine.mjs';
import {AREAS,getNode,applyChoice} from '../story.mjs';
import {findPath,walkable} from '../world.mjs';
const choose=(s,id,index,dice)=>{const node=getNode(s,id);assert.ok(node.choices[index],`${id}[${index}] exists`);assert.ok(!node.choices[index].disabled,`${id}[${index}] enabled`);return applyChoice(s,node.choices[index],dice);};
function route(role,ending,low=false){const s=fresh('Ari',role);choose(s,'intro',0);choose(s,'introRoad',0);choose(s,'camp',1,[low?1:20]);choose(s,'gate',1,[low?1:20]);choose(s,'crossJump',0);choose(s,'villageIntro',0);choose(s,'ledger',0);if(ending==='share'){choose(s,'well',0);choose(s,'wellConsent',0);}choose(s,'bell',0);choose(s,'archiveIntro',0);choose(s,'mural',0);choose(s,'workbench',0);choose(s,'guardian',0);choose(s,'guardianProof',0);choose(s,'guardian',0);choose(s,'sanctumIntro',0);choose(s,'core',{release:0,renew:1,share:2}[ending]);choose(s,{release:'confirmRelease',renew:'confirmRenew',share:'confirmShare'}[ending],0);return s;}
for(const role of Object.keys(CLASSES))for(const ending of ['release','renew','share'])for(const low of [true,false])test(`${role}: ${ending}, ${low?'all failed':'all successful'} checks still complete`,()=>{const s=route(role,ending,low);assert.equal(s.ending,ending);assert.ok(s.hp>0);assert.equal(s.area,3);assert.equal(s.flags.guardianPeace,true);assert.ok(endingText(s).hook.includes('Aschenhafen'));const loaded=hydrate(JSON.parse(JSON.stringify(s)));assert.equal(loaded.ending,ending);assert.deepEqual(loaded.flags,s.flags);});
test('Third ending needs all three independent clues',()=>{const s=fresh();s.flags.ledger=true;s.flags.mural=true;assert.equal(evidence(s),2);assert.equal(getNode(s,'core').choices[2].disabled,true);assert.throws(()=>applyChoice(s,{ending:'share'}));s.flags.well=true;assert.equal(getNode(s,'core').choices[2].disabled,false);});
test('A natural 20 is not automatic skill success; a 1 can pass',()=>{assert.equal(check(fresh(), 'medicine',30,20).success,false);assert.equal(check(fresh(),'medicine',2,1).success,true);});
test('Advantage uses the higher roll without doubling the bonus',()=>{const r=check(fresh(),'investigation',15,2,17);assert.equal(r.total,20);assert.deepEqual(r.dice,[2,17]);});
test('Medicine parcel is distinct from healing potions',()=>{const s=fresh();choose(s,'camp',0);assert.equal(s.potions,2);assert.equal(s.flags.medicineGiven,true);});
test('Failed persuasion cannot be rerolled indefinitely',()=>{const s=fresh();choose(s,'guardian',1,[1]);assert.equal(s.flags.guardianTried,true);assert.equal(getNode(s,'guardian').choices[1].disabled,true);});
test('Rast heals once and cannot replenish potions',()=>{const s=fresh();s.hp=1;s.potions=0;choose(s,'restplace',0);assert.equal(s.hp,12);assert.equal(s.potions,0);s.hp=4;assert.equal(getNode(s,'restplace').choices[0].disabled,true);});
test('Combat hit, victory and critical damage',()=>{const s=fresh();startCombat(s,()=>10);s.combat.hp=4;const rolls=[20,6,6];const r=combatAction(s,'attack',()=>rolls.shift());assert.equal(r.result,'victory');assert.equal(s.flags.guardian,true);assert.equal(s.combat,null);});
test('Enemy defeat is recoverable and preserves evidence',()=>{const s=fresh();s.flags.ledger=true;s.hp=1;startCombat(s,()=>10);const rolls=[1,20,4,4];const r=combatAction(s,'attack',()=>rolls.shift());assert.equal(r.result,'defeat');assert.equal(s.combat,null);assert.equal(s.hp,6);assert.equal(s.flags.ledger,true);});
test('Cannot drink missing potions or skip enemy retaliation on a valid potion',()=>{const s=fresh();startCombat(s,()=>10);s.potions=0;assert.equal(combatAction(s,'potion').result,'no-potion');s.potions=1;s.hp=5;const r=combatAction(s,'potion',()=>2);assert.equal(s.potions,0);assert.equal(r.result,'turn');assert.equal(s.combat.round,2);});
test('Loaded saves reject invalid versions and roles, clamp stats, ignore arbitrary flags',()=>{assert.throws(()=>hydrate({version:2}));const s=fresh();s.hp=999;s.potions=999;s.flags={ledger:true,evil:true};const h=hydrate(s);assert.equal(h.hp,12);assert.equal(h.potions,2);assert.deepEqual(h.flags,{ledger:true});});
for(let area=0;area<4;area++)test(`All ${AREAS[area].name} hotspots are accessible`,()=>{for(const hot of AREAS[area].hotspots){let dest={x:hot.x,y:hot.y+(hot.id!=='back'?.075:0)};if(!walkable(area,dest.x,dest.y)){let best;for(let x=.15;x<.9;x+=.025)for(let y=.2;y<.91;y+=.025)if(walkable(area,x,y)){const dist=Math.hypot(x-hot.x,y-hot.y);if(!best||dist<best.dist)best={x,y,dist};}dest=best;}assert.ok(dest,hot.id);const path=findPath(area,{x:AREAS[area].start[0],y:AREAS[area].start[1]},dest);assert.ok(path.length||Math.hypot(dest.x-AREAS[area].start[0],dest.y-AREAS[area].start[1])<.06,hot.id);for(const p of path)assert.ok(walkable(area,p.x,p.y));}});
test('A committed ending cannot be silently overwritten',()=>{const s=route('wanderer','release');applyChoice(s,{ending:'renew'});assert.equal(s.ending,'release');});

test('Earlier saves keep progress but remove companion-era journal and flags',()=>{const raw=fresh();delete raw.storyRevision;raw.area=2;raw.flags={intro:true,ledger:true,well:true,confession:true,forgiven:true};raw.journal=[{title:'Mara',text:'Alte Geschichte'}];const loaded=hydrate(raw);assert.equal(loaded.area,2);assert.equal(loaded.flags.ledger,true);assert.equal(loaded.flags.confession,undefined);assert.equal(loaded.recapPending,true);assert.ok(!JSON.stringify(loaded.journal).includes('Mara'));assert.equal(hydrate(loaded).recapPending,true);});
test('Core cannot reveal endings before player reads operating instructions',()=>{const s=fresh();s.area=3;assert.equal(getNode(s,'core').choices[0].area,2);assert.throws(()=>applyChoice(s,{ending:'release'}));});
test('Unvisited messenger is introduced in every ending without false prior familiarity',()=>{for(const ending of ['release','renew','share']){const s=fresh();s.ending=ending;assert.match(endingText(s).text,/Er heißt Iven/);assert.doesNotMatch(endingText(s).text,/Mara/);assert.match(endingText(s).hook,/Elin/);}});
test('Village return does not repeat the medicine delivery',()=>{const s=fresh();s.flags.villageIntro=true;assert.doesNotMatch(getNode(s,'villageIntro').text,/stellst das Medizin/);});
test('Failed care can be followed by medicine without using healing potions',()=>{const s=fresh();choose(s,'camp',1,[1]);assert.ok(!s.flags.ivenSaved);choose(s,'camp',0);assert.ok(s.flags.ivenSaved);assert.equal(s.potions,2);});
test('Solo preparation spends a turn and gives advantage to next attack',()=>{const s=fresh();startCombat(s,()=>10);combatAction(s,'focus',()=>1);assert.equal(s.combat.insight,true);assert.equal(s.combat.round,2);const dice=[1,20,2,2,1];combatAction(s,'attack',()=>dice.shift());assert.equal(s.combat.insight,false);assert.ok(s.combat.hp<16);});
